#!/bin/sh

# run this script being in the same directory
# i.e. run `cd src/query/parser/grammar`
# and then run `sh generate.sh`
rm -r autogenerated/*
java -jar ../../../../third_party/antlr-4.13.1-complete.jar -Dlanguage=Cpp IIC3413DBLexer.g4  -o autogenerated -no-listener -visitor
java -jar ../../../../third_party/antlr-4.13.1-complete.jar -Dlanguage=Cpp IIC3413DBParser.g4 -o autogenerated -no-listener -visitor
